### ISSUE TITLE
Problems with uploading mapping.txt file for de-obfuscation

### ISSUE THREAD

**Issue by batadamnjanovic** [DataDog/dd-sdk-android-gradle-plugin#65]
Hi!

I have a problem with uploading mapping.txt for de-obfuscation on Android.

One problem is that the `uploadMappingProductionRelease` task is called on CI/CD in the configuration phase and not after the `minifyProductionReleaseWithR8` task is finished , so the mapping.txt file is not created yet.
```
Task :app:uploadMappingProductionRelease
There's no mapping file /home/runner/work/android/android/app/build/outputs/mapping/productionRelease/mapping.txt, nothing to upload 
```

So I tried to upload it manually and got this error:
```
> Task :app:uploadMappingProductionRelease
Error uploading the mapping file for com.myapp.app.android:v1.31.0 {variant:production}
java.net.ConnectException: Failed to connect to sourcemap-intake.datadoghq.eu/2600:1901:0:606b:0:0:0:0:443
```

Do you have any advice what to do?
Thanks!

**Comment by 0xnm** [comment]
Hi @batadamnjanovic! Our upload mapping task indeed doesn't depend on any task, since it is supposed to be run on-demand only. In case of CI/CD setup you can simply wire this task to the mapping generation task, something like this should work (Kotlin Script used):

```kotlin
    tasks.named("uploadMappingProductionRelease") {
        dependsOn("minifyProductionReleaseWithR8")
    }
```

Or you may use other way around, with `finalizedBy`.

Regarding connectivity to `sourcemap-intake.datadoghq.eu`: I would suggest to check the network rules of the build machine, it may be the case that outbound traffic is allowed only per whitelist. You may simply check domain availability by doing `ping` or `curl -I https://sourcemap-intake.datadoghq.com`. Other reason of connectivity failure can be old certificates chain on the build machine, so handshake with the server cannot be done.

**Comment by batadamnjanovic** [comment]
Thanks @0xnm.

This is how it looks
```
tasks.register("uploadDatadogMappingFile") {
    val shrinkTask = tasks["shrinkProductionReleaseResources"]
    val uploadMappingTask = tasks["uploadMappingProductionRelease"]
    dependsOn(shrinkTask)
    uploadMappingTask.mustRunAfter(shrinkTask)
    finalizedBy(uploadMappingTask)
}
```

**Comment by 0xnm** [comment]
@batadamnjanovic Current de-obfuscation works only for error tracking for now (we may expand it to Logs/Analytics in future). Do you see de-obfuscated entries in the [Error Tracking](https://app.datadoghq.com/rum/error-tracking)? De-obfuscation doesn't propagate backwards, so only events which happened after mapping file upload will be de-obfuscated.

If you don't see de-obfuscated events in the Error Tracking, please make sure that mapping file uploaded is exactly for the same `apk` which submits events (means `versionName` is the same, `serviceName` is the same (by default it is application ID), and if you have flavors - SDK `Credentials#variant` has a value of `BuildConfig.FLAVOR`).

**Comment by batadamnjanovic** [comment]
@0xnm does that mean that RUM must be enabled? Our decision was to go with Logs/Analytics, as we don't need advanced logs(RUM) and because the price is much higher for RUM logs. Now I am not sure if I understood everything correctly regarding RUM vs Logs/Analytics.

**Comment by batadamnjanovic** [comment]
@0xnm, we've enabled RUM and now it'll go with the next release. Thanks for help!
